### ISSUE TITLE
Scripts for building and running Macro in a native environment

### ISSUE THREAD

**Issue by Hanseltu** [jhu066/Marco#1]
Hi,

Thank you for sharing the nice tool!

May I know if it is possible to provide the scripts for building & running Marco in a native environment? The current docker running environment is good for reproducing the results but it might not be easy for me to debug the tool and make further contributions to the tool. So, it would be great and helpful if you could share the scripts or building and running (maybe a single benchmark is enough) Marco natively.

Many thanks and have a great day!

Best regards,
Haoxin

**Comment by jhu066** [comment]
Hello Haoxin,

For building and running Marco in a native environment, you can refer to the Dockerfile, which lists all the necessary packages and dependencies. This should guide you in setting up your local environment for building and running the tool. While we currently do not have standalone scripts for native installation, using the Dockerfile as a reference can be a helpful starting point.

Thanks,
Jie

**Comment by Hanseltu** [comment]
Thank you, Jie! I will try.
