### ISSUE TITLE
Release seeds for all test programs

### ISSUE THREAD

**Issue by Hanseltu** [jhu066/Marco#2]
Hi,

I noticed that the repository is missing test seeds for certain test programs (e.g., `swftools`). May I know if you plan to release the missing seeds for the rest of the test programs evaluated in the paper?

Many thanks,
Haoxin

**Comment by jhu066** [comment]
Programs No. 17 to 30 in Table 5 of Marco paper are from Unibench dataset. You can find the seeds here:
https://github.com/unifuzz/seeds/tree/master

**Comment by Hanseltu** [comment]
Thanks!
